name: f1_server
description: Starting point for a Serverpod server.
version: 1.1.0+2
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  serverpod: ^0.9.8

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.0.5
  json_serializable: ^6.3.1
  lints: ^1.0.1
